import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  ArrowLeft,
  BadgeCheck,
  Ban,
  Boxes,
  CalendarRange,
  Camera,
  ChartColumn,
  ChevronDown,
  ClipboardList,
  Clock,
  Factory,
  FileSpreadsheet,
  Download,
  Home,
  Maximize2,
  Package,
  Pencil,
  RefreshCw,
  Ruler,
  Save,
  Scale,
  ScanSearch,
  Scissors,
  Search,
  Square,
  Tag,
  Upload,
  UserCog,
  Users,
  Wallet,
  Warehouse,
} from "lucide-react";

/** Canonical lucide map — no emoji in UI. */
export const APP_ICONS = {
  home: Home,
  calendar: CalendarRange,
  clipboard: ClipboardList,
  scan: ScanSearch,
  badgeCheck: BadgeCheck,
  factory: Factory,
  package: Package,
  boxes: Boxes,
  ban: Ban,
  clock: Clock,
  camera: Camera,
  refresh: RefreshCw,
  chart: ChartColumn,
  warehouse: Warehouse,
  users: Users,
  wallet: Wallet,
  userCog: UserCog,
  search: Search,
  pencil: Pencil,
  save: Save,
  fileSpreadsheet: FileSpreadsheet,
  download: Download,
  upload: Upload,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  ruler: Ruler,
  maximize: Maximize2,
  square: Square,
  scissors: Scissors,
  scale: Scale,
  tag: Tag,
  alert: AlertTriangle,
} as const;

export type AppIconName = keyof typeof APP_ICONS;

export function getAppIcon(name: AppIconName): LucideIcon {
  return APP_ICONS[name];
}
